import Config

# Cache manifest with the digested versions of the static files (generated by
# `mix assets.deploy`, which runs before the server starts).
config :{{app}}, {{App}}Web.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is COMPILE-TIME in Phoenix: it is decided when the image is built.
# To deploy over plain HTTP (VPN/LAN with no TLS terminator) build with
# DISABLE_FORCE_SSL=1 and set PHX_SCHEME=http at runtime.
# (The skeleton default is HTTPS; see SPEC-docker.md §Hard rules.)
if System.get_env("DISABLE_FORCE_SSL") != "1" do
  config :{{app}}, {{App}}Web.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: [hosts: ["localhost", "127.0.0.1"]]
    ]
end

# Swoosh's HTTP client.
config :swoosh, api_client: Swoosh.ApiClient.Req

# Swoosh does not keep mail in memory in prod.
config :swoosh, local: false

# No debug noise in production.
config :logger, level: :info

# Runtime configuration (environment variables) lives in config/runtime.exs.
